package sist.backend.domain.user.entity;

public enum ActivityType {
    HOTEL_RESERVATION, HOTEL_RESERVATION_CANCEL, PASSWORD_CHANGE, PAYMENT, DINING_RESERVATION, PAYMENT_CANCEL, ACCOUNT_DELETE, LOGIN, LOGOUT,
    ADMIN_GIFT_CREATE, ADMIN_GIFT_UPDATE, ADMIN_GIFT_DELETE, PAYMENT_FAILED
}

