package sist.backend.infrastructure.logging;

public enum ActivityType {
    HOTEL_RESERVATION, PASSWORD_CHANGE, PAYMENT, DINING_RESERVATION, PAYMENT_CANCEL, ACCOUNT_DELETE, LOGIN, LOGOUT, ADMIN_GIFT_CREATE, ADMIN_GIFT_UPDATE, ADMIN_GIFT_DELETE,
    DINING_RESERVATION_UPDATE, QNA_ANSWER
}
