spring:
  profiles:
    active: dev
    include: secret
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  security:
    jwt:
      secret: 3c1fdk93k9d209fk09sdkf033kd93k90
      expiration: 36000000  # 10시간 (밀리초 단위)
      header: Authorization
      prefix: Bearer
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ted19horse.mysql.database.azure.com:3306/chill?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: sist
    password: 1111

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

server:
  port: 8080
 
