spring:
  profiles:
    active: dev
    include: secret, mail # 문의 메일 발송
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  security:
    jwt:
      secret: ${JWT_SECRET_KEY}
      expiration: 36000000
      header: Authorization
      prefix: Bearer
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

server:
  port: 8080
